server:
  port: ${PORT}

spring:
  application:
    name: fbk-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/khoaDLuu/fbk-cloud-config.git
          default-label: main
          clone-on-start: true

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  registryFetchIntervalSeconds: 60
  region: default
  serviceUrl.defaultZone: ${SERVICE_DISCOVERER_URL}/eureka/
